### PR TITLE
Support POST requests

### PR DESCRIPTION
**Pull request by danielmohacsi**
@angelim 

We were in the need of POST support, because one of our services uses POST for event tracking.

### CODE REVIEW

**Comment by angelim** [comment]
Thanks, @danielmohacsi. I'll fix some broken tests and merge it locally.

**Comment by rgabo** [comment]
@angelim have you had a chance to check out this PR? I was just looking for the exact same functionality :smile:

**Comment by angelim** [comment]
I'm so sorry for the delay on this.

I've used most of @danielmohacsi and @htamas implementation, but with a slightly different approach to avoid repetition and allow better testability. Now an instance of Snowly service spins up when running the specs, so I finally got some integration tests in using the snowplow-tracker ruby gem.

I don't think this will have any impact on your workflow, but now all responses are encapsulated inside a json array for the sake of consistency.

This feature has been published on the latest version at RubyGems, if you'd like to check it out.

Thanks @danielmohacsi and @htamas.

**Comment by danielmohacsi** [comment]
Thanks for working on it! I will test drive this with the js tracker next
week.

**Pull request closed without merging**
